### ISSUE TITLE
Syncing with serialized attributes doesn't work

### ISSUE THREAD

**Issue by KevinGamer3D2** [argon-rbx/argon#27]
Syncing with serialized attributes doesn't seem to work in studio.
![image](https://github.com/argon-rbx/argon/assets/63291726/ea67f0f2-96fe-47ab-bc79-e203fea7b6b2)
![image](https://github.com/argon-rbx/argon/assets/63291726/bc9d9e5b-cb81-4a97-bde9-1423a78bca28)

**Comment by DervexDev** [comment]
Okay, so it's a bug in the documentation as it is related to `rbx-dom` (see https://github.com/rojo-rbx/rojo.space/pull/74). In short, you should just use `Attributes`. I'm going to remove `AttributesSerialized` from the docs.
