### ISSUE TITLE
problem with dsiabled scripts in-game

### ISSUE THREAD

**Issue by henri14871** [argon-rbx/argon#28]
for some reason argon wants to write '--disable' on the first line of every disabled script, this is an issue when you want to be able to reenable the script and this broke a grenade framework in my game.

**Comment by DervexDev** [comment]
This is intended as you need to control this property from the editor easily. I'm not sure why it is a problem for you though. If you want the script to be enabled you can just remove `--disable` flag.

**Comment by henri14871** [comment]
I have a script that is enabled and duplicated to an object ingame, it's starts of disabled obviously but when argon puts --disabled on the first line it also commented out an important variable which is used in the script that broke the entire script.

**Comment by DervexDev** [comment]
Can confirm that this is a bug. `--disable` flag should add a line break.

**Comment by DervexDev** [comment]
Fixed in 19203d5a4c0687f314aef5a3c0e92df57ed433e3
