### ISSUE TITLE
rojo_mode doesn't work

### ISSUE THREAD

**Issue by amthius** [argon-rbx/argon#47]
Unless I am using `rojo_mode` incorrectly here, I would assume by its definition **"When enabled Argon will use [Rojo](https://rojo.space/) namespace by default when creating a new project"** it would use `init` instead of `.src`

![image](https://github.com/argon-rbx/argon/assets/51867420/db9c7105-501e-46a0-ba4a-47eb16a40b9b)

OS: ``Windows 11``
CLI Argon: ``argon-rbx 2.0.7``
VSC Argon: `v2.0.5`
Plugin Argon: `V2.0.6`

**Comment by DervexDev** [comment]
Fixed in 9613541cc7f9146c945d7624b30352231e0bbecf
