### ISSUE TITLE
argon-2.0.8-windows-x86_64.zip flagged as Trojan

### ISSUE THREAD

**Issue by seyaidev** [argon-rbx/argon#50]
Trying to download the latest CLI for Windows but it's being flagged as a trojan. Previous versions work fine

**Comment by DervexDev** [comment]
That's weird. I updated the Windows binary with a manually built one and it seems to be fine now. Could you verify that?

**Comment by DervexDev** [comment]
Closing this issue since the new binary is no longer flagged as a trojan.
