### ISSUE TITLE
`Lighting.Technology` property does not sync

### ISSUE THREAD

**Issue by DervexDev** [argon-rbx/argon#59]
Not sure if I'm using it wrong but I can't set `Lighting.Technology` through my `project.json` file? I tried in both implicit and explicit formats:

![image](https://github.com/argon-rbx/argon/assets/118916772/8a489860-ba6b-47de-a021-56e9c243c4a2)
---
![image](https://github.com/argon-rbx/argon/assets/118916772/f68bcb06-fb80-4edb-9c70-9a8551b4fe69)

I also tried changing other props and they change and they are shown in the output window, however the `Technology` property doesn't even appear here.
![image](https://github.com/argon-rbx/argon/assets/118916772/252afc84-ffae-4c22-8bf5-30a08d99365e)

**EDIT**: Just realized that you have to put the value of the enum, which I also tried but it still didn't work.

_Originally posted by @AridAjd in https://github.com/argon-rbx/argon/discussions/24#discussioncomment-9857112_

**Comment by AridAjd** [comment]
repro: https://streamable.com/hk6e3t

**Comment by DervexDev** [comment]
Oh, I forgot that `Lighting.Technology` is [not scriptable](https://create.roblox.com/docs/reference/engine/classes/Lighting#Technology). The only way to bypass this limitation is to use `argon build`.
