### ISSUE TITLE
Templates are either missing or not referenced correctly on Linux, cannot init a project.

### ISSUE THREAD

**Issue by Pyram1d-dev** [argon-rbx/argon#61]
After installing Argon CLI and the VSCode extension, I cannot init a project due to the templates either being missing or not detected. I installed the extension from the VSIX using VSCodium and I am running Arch Linux, though I've also tried properly installing the extension through VSCode and I still have the same issue.
![image](https://github.com/argon-rbx/argon/assets/76640329/31cc7c88-2966-4cd7-beb5-d29da0aefde5)
![image](https://github.com/argon-rbx/argon/assets/76640329/bf3f965c-9ac0-4e5c-aef3-3dc77a7caab7)

**Comment by DervexDev** [comment]
Could you verify that templates installed in `~/.argon/templates/` exist? On Ubuntu 22 both CLI and VS Code extension work just fine:
![image](https://github.com/argon-rbx/argon/assets/78505208/d7b338d1-6427-4d2d-9ac0-9ab9fd91a80f)

**Comment by Pyram1d-dev** [comment]
There was nothing in the directory. I'm really not sure why it didn't install automatically, but downloading the templates from the repo and inserting them into the directory manually seems to have done the job, and I can now properly init a project. This was probably an issue with my system. Thanks!
