### ISSUE TITLE
use_wally improvements

### ISSUE THREAD

**Issue by Aristosis** [argon-rbx/argon#71]
The `/Packages` directory usually created by utilities like Wally is present in the autogenerated `.gitignore` which can cause the Packages to not be added to the game, as _argon does not look for file changes in the directory_.
This can be fixed by making `use_wally` true in the config, but shouldn't that be the default, making it ignore Packages explicitly instead of implicitly? Why is it even ignored if the option is set to false? What do you think of adding the Package directory to the `project.json` when initializing a new project, and add another config to change it from the default directory for the templates and instead use a different folder?

**Comment by DervexDev** [comment]
> What do you think of adding the Package directory to the `project.json` when initializing a new project, and add another config to change it from the default directory for the templates and instead use a different folder?

I understand this part and I think it's a good idea, but I'm not sure what you mean here:

> The `/Packages` directory usually created by utilities like Wally is present in the autogenerated `.gitignore` which can cause the Packages to not be added to the game, as _argon does not look for file changes in the directory_.

`.gitignore` has nothing to do with how Argon processes file changes.

**Comment by Aristosis** [comment]
I had a sneaky suspicion that it might have been the case as when I was testing this, I noticed that the packages folder was _untracked_. Must've been something else that I fixed then. Still no clue why it's in the `.gitignore` tho... don't really see an issue with it being in the git by default

**Comment by DervexDev** [comment]
> Still no clue why it's in the `.gitignore` tho... don't really see an issue with it being in the git by default

It doesn't make sense to have packages in source control. Users should install them with Wally every time they clone the repo. That's exactly how npm or cargo works.

> Also is that all that the `use_wally` config does?

Right now it's the equivalent of `--wally` option when running `argon init` command.

> Just remove it from the `gitignore`?

If you don't want Argon to add `/Packages` to your `.gitignore` just remove it from the desired template.

**Comment by DervexDev** [comment]
Added in [2.0.11](https://github.com/argon-rbx/argon/releases/tag/2.0.11)
