### ISSUE TITLE
Few errors and suggestions

### ISSUE THREAD

**Issue by ari-party** [argon-rbx/argon#87]
While "porting" existing game.

![image](https://github.com/user-attachments/assets/ff6fe8c4-ba70-4481-965e-35e9a6202d80)

You cannot have multiple instances with the same name, maybe automatically assign a number (Instance1, Instance2) with a .data.json including the name?

You can't have characters like `/` in the name which are quite commonly used for mesh names, replace with a `-` or remove and use .data.json to set the name?

`ERROR: Failed to parse property: Cannot unambiguously resolve the value Array3([1.257019, 2.071988, 0.079055]) [argon::middleware::data:78]`

**Comment by DervexDev** [comment]
> You cannot have multiple instances with the same name, maybe automatically assign a number (Instance1, Instance2) with a .data.json including the name?
> 
> You can't have characters like `/` in the name which are quite commonly used for mesh names, replace with a `-` or remove and use .data.json to set the name?

Love these! Definitely going to be implemented in version `2.0.17` as `2.0.16` is already scheduled.

> `ERROR: Failed to parse property: Cannot unambiguously resolve the value Array3([1.257019, 2.071988, 0.079055]) [argon::middleware::data:78]`

Could you provide the `.data.json` file that causes it?

**Comment by ari-party** [comment]
> > You cannot have multiple instances with the same name, maybe automatically assign a number (Instance1, Instance2) with a .data.json including the name?
> > You can't have characters like `/` in the name which are quite commonly used for mesh names, replace with a `-` or remove and use .data.json to set the name?
> 
> Love these! Definitely going to be implemented in version `2.0.17` as `2.0.16` is already scheduled.
> 
> > `ERROR: Failed to parse property: Cannot unambiguously resolve the value Array3([1.257019, 2.071988, 0.079055]) [argon::middleware::data:78]`
> 
> Could you provide the `.data.json` file that causes it?

I'm actually not sure what instance's .data.json causes it, what type of properties can cause this error?

**Comment by DervexDev** [comment]
`Color3`, `Color3uint8`, `Vector3` and `Vector3int16`

**Comment by ari-party** [comment]
> `Color3`, `Color3uint8`, `Vector3` and `Vector3int16`. There is also a big chance that `2.0.16` will fix it.

I'll wait for that release! If you haven't already, adding more details to errors like the path of the instance would be great. (if realistic & possible)

**Comment by DervexDev** [comment]
> ERROR: Failed to parse property: Cannot unambiguously resolve the value Array3([1.257019, 2.071988, 0.079055]) [argon::middleware::data:78]

Fixed in `2.0.17`.

Had to delay the rest of the stuff to `2.0.18` as `2.0.17` contains important fixes.

**Comment by DervexDev** [comment]
> You cannot have multiple instances with the same name, maybe automatically assign a number (Instance1, Instance2) with a .data.json including the name?

Available in `2.0.18` - instead of a number a UUID v4 is assigned for performance reasons.

> You can't have characters like / in the name which are quite commonly used for mesh names, replace with a - or remove and use .data.json to set the name?

Available in `2.0.18` - forbidden characters are removed completely.

> While "porting" existing game.

Argon plugin `2.0.11` should fix this issue.
