### ISSUE TITLE
Argon plugin automatically installs itself when using any command

### ISSUE THREAD

**Issue by ari-party** [argon-rbx/argon#93]
Whenever I run `argon`, or any command that isn't `argon plugin uninstall`, the plugin reinstalls itself. I have not created a global configuration.

**Comment by AridAjd** [comment]
Do you have a configuration file in the local directory (`argon.toml`)? Also you can try changing the `install_plugin` config to `false`

**Comment by ari-party** [comment]
> Do you have a configuration file in the local directory (`argon.toml`)? Also you can try changing the `install_plugin` config to `false`

No configs anywhere! I was running the command in a fresh terminal (in C:/Users/x)

**Comment by AridAjd** [comment]
> > Do you have a configuration file in the local directory (`argon.toml`)? Also you can try changing the `install_plugin` config to `false`
> 
> No configs anywhere! I was running the command in a fresh terminal (in C:/Users/x)

Pretty sure, you can create your own config file (locally or in your main `.argon` folder) using `argon config` or you can create your own config file in the local directory (project you are working in) and just create a `argon.toml` file.

**Comment by ari-party** [comment]
> > > Do you have a configuration file in the local directory (`argon.toml`)? Also you can try changing the `install_plugin` config to `false`
> > 
> > 
> > No configs anywhere! I was running the command in a fresh terminal (in C:/Users/x)
> 
> Pretty sure, you can create your own config file (locally or in your main `.argon` folder) using `argon config` or you can create your own config file in the local directory (project you are working in) and just create a `argon.toml` file.

That's not the point! I don't have a config and the plugin installs itself automatically.
![image](https://github.com/user-attachments/assets/b555ccdd-2514-47bd-8d41-b134f52c41ab)

**Comment by AridAjd** [comment]
> That's not the point! I don't have a config and the plugin installs itself automatically.

That's what I said? Create a config file using the prompt and do `install_plugin = false`

**Comment by DervexDev** [comment]
Argon installs the Roblox Studio plugin by default as it's recommended. If you don't want Argon to do it you have to create the config and set `install_plugin = false` as @AridAjd said.

**Comment by ari-party** [comment]
> Argon installs the Roblox Studio plugin by default as it's recommended. If you don't want Argon to do it you have to create the config and set `install_plugin = false` as @AridAjd said.

This is very weird behavior by default.

**Comment by DervexDev** [comment]
It was implemented back when there wasn't a plugin auto-update option. I left it enabled as the upcoming "automatic dom updates" feature will require the plugin to be installed like this.
