### ISSUE TITLE
Sourcemap does not include JSON model files

### ISSUE THREAD

**Issue by AridAjd** [argon-rbx/argon#95]
The title is self-explanatory. Basically, sourcemap will not include files which are model files. I have found a temporary fix where you add the model into the `sourcemap.json` and turn off generate sourcemap but this isn't ideal.

```json
{
	"name": "Hover",
	"className": "Sound",
	"filePaths": [
		"src\\shared\\Assets\\SFX\\Hover.model.json"
	]
}
```

**Comment by DervexDev** [comment]
What do you store in your `Hover.model.json`? If there are no scripts you need to run `sourcemap` command with the `--non-scripts` option.

**Comment by AridAjd** [comment]
> What do you store in your `Hover.model.json`? If there are no scripts you need to run `sourcemap` command with the `--non-scripts` option.

The model is just a `Sound` instance and nothing else. Also, pretty sure that the VSCode extension does not have "Include non scripts" when serving.

**Comment by DervexDev** [comment]
> Also, pretty sure that the VSCode extension does not have "Include non scripts" when serving.

Nor does the CLI.

> Do feel like it could be a tidy bit better if there was a non-scripts option in the serve.

If you want to customize how sourcemap is generated you should run two Argon instances - `serve` and `sourcemap`. I won't add the `--non-scripts` option for `serve` and `build` commands as it's unrelated to them and the CLI will get too messy. Not to mention I would also have to add other `sourcemap` options.

**Comment by AridAjd** [comment]
Understand the concern. Thanks for the answer!
